db:
    host: localhost
    port: 5432
    dbname: rcb
    user: some_user
    password: some_pw

github-app-id: "87729"
github-client-id: "Iv1.8f11845b87ff14f0"
github-client-secret: "fooop"
github-app-key-file: "rakudocibot.2020-11-06.private-key.pem"
projects:
    rakudo:
        project: rakudo
        repo: rakudo
        main: main
        slug: rakudo/rakudo
        install-id: 20243470
    nqp:
        project: Raku
        repo: nqp
        main: main
        slug: Raku/nqp
        install-id: 20243470
    moar:
        project: MoarVM
        repo: MoarVM
        main: master
        slug: MoarVM/MoarVM
        install-id: 20243470

hook-url: https://cibot.rakudo.org/
jwt-secret: "N#xTe4>IGSWfH#M&MYXxI~#w9yj@X8X/g8-N{;n)5D>kFh~AaW"

obs-user: some_user
obs-password: "some_pw"

obs-check-duration: 30
obs-min-run-duration: 300 # 5 * 60
obs-build-end-poll-interval: 15
obs-packages:
    - moarvm
    - nqp-moarvm
    - rakudo-moarvm

github-check-batch-count: 15
github-max-source-retrieval-retries: 5

sac-work-dir: work/sac-work
sac-store-dir: work/sac-store
obs-work-dir: work/obs-work

sac-cleanup-interval: 3600 # 60 * 60
source-archive-retain-days: 60

flapper-list-url: https://raw.githubusercontent.com/Raku/RakudoCIBot/main/flapper-list.yml

testset-manager-interval: 300 # 5 * 60
github-requester-interval: 300 # 5 * 60
obs-interval: 300 # 5 * 60
flapper-list-interval: 3600 # 60 * 60

web-host: 0.0.0.0
web-port: 10000

log-level: TRACE
